<?php
/*
 * US States Array
 */
$counties = array(
    'MBS'=>'Mombasa',
    'KWL'=>'Kwale',
    'KLF'=>'Kilifi',
    'TR'=>'Tana River',
    'LMU'=>'Lamu',
    'TT'=>'Taita Taveta',
    'GRS'=>'Garissa',
    'WJR'=>'Wajir',
    'MDR'=>'Mandera',
    'MBT'=>'Marsabit',
    'ISL'=>'Isiolo',
    'MRU'=>'Meru',
    'TN'=>'Tharaka-Nithi',
    'EBU'=>'Embu',
    'KTI'=>'Kitui',
    'MKS'=>'Machakos',
    'MNI'=>'Makueni',
    'ND'=>'Nyandarua',
    'NRI'=>'Nyeri',
    'KR'=>'Kirinyaga',
    'MG'=>'Murang’a',
    'KB'=>'Kiambu',
    'TK'=>'Turkana',
    'WP'=>'West Pokot',
    'SB'=>'Samburu',
    'TN'=>'Trans-Nzoia',
    'UG'=>'Uasin Gishu',
    'EM'=>'Elgeyo-Marakwet',
    'NND'=>'Nandi',
    'BRG'=>'Baringo',
    'LKP'=>'Laikipia',
    'NKR'=>'Nakuru',
    'NRK'=>'Narok',
    'KJD'=>'Kajiado',
    'KRC'=>'Kericho',
    'BMT'=>'Bomet',
    'KKM'=>'Kakamega',
    'VHG'=>'Vihiga',
    'BNM'=>'Bungoma',
    'BSA'=>'Busia',
    'SAY'=>'Siaya',
    'SMU'=>'Kisumu',
    'HB'=>'Homa Bay',
    'MGR'=>'Migori',
    'KSI'=>'Kisii',
    'NMR'=>'Nyamira',
    'NRB'=>'Nairobi',
);